### ISSUE TITLE
Use standard HTML elements for the table

### ISSUE THREAD

**Issue by chrisgrieser** [trey-wallis/obsidian-notion-like-tables#28]
tables in Obsidian use normal HTML, e.g. `table`, `tr`, `thead` etc. When a plugin also uses tables and also uses those types, this has the advantage that all the styling the themes apply to tables it also applied to the plugin's tables.

Right now, this plugin uses only `div` as type, which is why the tables will not render nicely in themes, unless they put in the time to remake all their styling.
<img width="553" alt="Screenshot 2022-04-10 11 33 46" src="https://user-images.githubusercontent.com/73286100/162612048-5e24e043-898b-4dd4-9ea1-e88cba131b7b.png">

**Comment by trey-wallis** [comment]
Hi Chris,

Thank you for this feature request. Using divs instead of semantic tags is a habit I've gotten into when building virtualized tables. Although, in this case I choose to do it so that the app would be easier to build. I do see the case that if a user was using a custom theme and was using this plugin to render all their tables, that it would be beneficial to have their theme style the NLT as if it were a normal rendered table.

I will add this to my upcoming features list.

Thank you again,
Trey.

**Comment by trey-wallis** [comment]
Added in v0.2.0
