### ISSUE TITLE
content disappear

### ISSUE THREAD

**Issue by minecci** [trey-wallis/obsidian-notion-like-tables#302]
### Describe the bug

Content disappears after viewing other notes

### Steps to reproduce

Content disappears after viewing other notes!

### Expected behavior

Content don't disappear

### Are you using the mobile app?

No

### Obsidian debug info

     Content disappears after viewing other notes

**Comment by m-paul** [comment]
(This comment is replying to the above, but also includes two other topics)

Topic 1: This bug happened to me as well. I see my table's data in the data.json file, but the markdown file containing the table is blank. I was able to reconstitute the table via the data.json file.

Topic 2: Also noticed that the data.json file contains data for tables I've previously deleted.

Topic 3: Question: Does anyone know why the developer\designer decided there was a need for a data.json file? I feel like everything it's doing can be handled in markdown and YAML (which would improve portability and prevent data duplication).
 - Since the plug-in controls the markdown file containing the table, Column Ids can be handled via column names like this: "col:[Unique ID]:[Display Name]" (ex: col:Kq1iHUwa:User Name)
 - Same can be said of row ID - this can be inferred from row number and if multiple custom orderings are needed, you could add a column named something like "order:[Unique Id]" (leaving off the display name so that the plugin doesn't show the column)
 - Column definitions could then be described in YAML, referencing the column id

**Comment by trey-wallis** [comment]
Fixed in 6.0.0
