### ISSUE TITLE
table setting disappear after uninstall then reinstall NLT plugin or delete the "notion-like-tables\data.json" 

### ISSUE THREAD

**Issue by Linzeal** [trey-wallis/obsidian-notion-like-tables#303]
### Describe the bug

after uninstall then reinstall NLT plugin or delete the ".obsidian\plugins\notion-like-tables\data.json" ,all NLT table settings disappear, such as Cell Types, Column Resizing. It's better to save NLT table settings in each table definition file.

### Steps to reproduce

uninstall then reinstall NLT plugin or delete the NLT plugin setting file ".obsidian\plugins\notion-like-tables\data.json"

### Expected behavior

NLT table settings is separated from NLT plugin setting file "notion-like-tables\data.json".  It's better to save NLT table settings in each table definition file.

### Are you using the mobile app?

Yes

### Obsidian debug info

none

**Comment by m-paul** [comment]
I feel like everything it's doing can be handled in markdown and YAML (which would improve portability and prevent data duplication).
 - Since the plug-in controls the markdown file containing the table, Column Ids can be handled via column names like this: "col:[Unique ID]:[Display Name]" (ex: col:Kq1iHUwa:User Name)
 - Same can be said of row ID - this can be inferred from row number and if multiple custom orderings are needed, you could add a column named something like "order:[Unique Id]" (leaving off the display name so that the plugin doesn't show the column)
 - Column definitions could then be described in YAML, referencing the column id

**Comment by trey-wallis** [comment]
This was very problematic. Fixed in 6.0.0
