### ISSUE TITLE
Live Preview support?

### ISSUE THREAD

**Issue by sinewave** [trey-wallis/obsidian-notion-like-tables#95]
Soo excited about the progress on this plugin and where it’s headed.

Wanted to ask if live preview/edit support is on the roadmap for a future release?

**Comment by trey-wallis** [comment]
@sinewave Hi sinewave. Thank you for your feature request. What functionality are you expecting? Can you give me some specific examples?

**Comment by Ampa** [comment]
Came to ask the same question, though I am not sure that I've really thought it through...

It is a little awkward to have to create the table in Live Preview mode, and then switch to Reading mode in order to use the Notion-like functionality.

I work in Live Preview 99.9% of the time, so ideally all features would be accessible in Live Preview.

However... This may not be possible, since clicking into the table would cause Live Preview to show the underlying markdown, removing the effects of the plugin?

**Comment by FriedrichStein** [comment]
Would love to use it in live view! 
Amazing plug-in! Thanks!

**Comment by sinewave** [comment]
> Hi sinewave. Thank you for your feature request. What functionality are you expecting? Can you give me some specific examples?

Similar to what others have said I'm in edit mode 99.99% of the time. Not sure what's technically possible but ideally I'd love to be able to do all the same things in reading mode while in edit mode 😄

**Comment by trey-wallis** [comment]
@isle9 Do you have any specific plugins that I could look into? I do not currently know how to do live preview support. I was thinking I might have to make a feature request on the Obsidian forums. But if you have some references of plugins where people were able to find a way around this, that would be very helpful!

**Comment by Quorafind** [comment]
I found when edit and input Chinese word on the edit mode(Live Preview), the character inputed will be duplicated.


https://user-images.githubusercontent.com/13215013/166481387-43115834-376f-4a5f-b18b-c5a5233ec45c.mp4

**Comment by trey-wallis** [comment]
@Quorafind Hi Quorafind. If this issue is still occurring for you, could you open a bug issue. Thanks.

**Comment by trey-wallis** [comment]
@sinewave I will be looking into this this week. I'm trying to get a few other things implemented first. I think I should be able to implement something though. I found another plugin repository that seems promising for what I want to do.

**Comment by MugenLee** [comment]
> @isle9你有任何我可以研究的特定插件吗？我目前不知道如何进行实时预览支持。我在想我可能不得不在 Obsidian 论坛上提出功能请求。但是，如果您有一些插件参考，人们能够找到解决此问题的方法，那将非常有帮助！



> @isle9 Do you have any specific plugins that I could look into? I do not currently know how to do live preview support. I was thinking I might have to make a feature request on the Obsidian forums. But if you have some references of plugins where people were able to find a way around this, that would be very helpful!

Take a look at this plugin if you need:
https://github.com/windily-cloud/obsidian-AGtable

This plugin can be implemented in the live preview mode, using a table editing mode similar to Typora, for editing

this is exactly what i need
Because in "notion-like-tables", if the table is edited in the live preview mode, the code will be edited directly, and UI interface editing cannot be realized

And most users are currently using it in live preview mode

So if you can use "notion-like-tables" in live preview mode

I think this will be a very useful update

@trey-wallis 
good luck

**Comment by trey-wallis** [comment]
@sinewave I plan on diving into this and hopefully getting something worked out by the end of this week

**Comment by trey-wallis** [comment]
@MugenLee This was really helpful! I'm pushing out a basic update in a few minutes

**Comment by trey-wallis** [comment]
@MugenLee @Ampa  @Quorafind @FriedrichStein @blacksuan19 @dknight212 @imeed166. Basic live preview added in 3.5.0 :)

**Comment by trey-wallis** [comment]
For further requests for live preview, please open a new feature request. Thank you.
